# Generated by Django 5.2 on 2025-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
