# Generated by Django 5.2 on 2025-05-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
