# Generated by Django 5.2 on 2025-05-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0013_documentcategory_alter_document_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
