# Generated by Django 5.2 on 2025-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0015_remove_task_is_completed_task_due_date_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='new', max_length=20),
        ),
    ]
