# Generated by Django 5.2 on 2025-05-30 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0022_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
