# Generated by Django 5.2 on 2025-05-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0023_department_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='leader',
        ),
    ]
