# Generated by Django 5.2 on 2025-06-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0025_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
